<script>
  import { backendLabel, getPrimaryFinding, getPriorityAction, severityLabel, verdictLabel } from "./shared.js";

  export let result = null;

  $: primaryFinding = getPrimaryFinding(result);
  $: priorityAction = getPriorityAction(result);
</script>

{#if result}
  <section class="reviewer-results-section reviewer-results-overview">
    <div class="reviewer-section-header">
      <div>
        <div class="reviewer-kicker">How To Read This</div>
        <h3 class="reviewer-section-title">Review Overview</h3>
      </div>
    </div>

    <div class="reviewer-overview-grid">
      <article class="reviewer-overview-card">
        <span>Current Verdict</span>
        <strong>{verdictLabel(result.overall_verdict)}</strong>
        <p>The overall quality signal for the snippet right now.</p>
      </article>

      <article class="reviewer-overview-card">
        <span>Highest Risk</span>
        <strong>{severityLabel(result.risk_level)}</strong>
        <p>The strongest severity level found in the review.</p>
      </article>

      <article class="reviewer-overview-card">
        <span>Generated By</span>
        <strong>{backendLabel(result.backend)}</strong>
        <p>The reviewer backend that produced this analysis.</p>
      </article>

      <article class="reviewer-overview-card">
        <span>Best First Move</span>
        <strong>{primaryFinding ? primaryFinding.title : "Tighten the weakest area first"}</strong>
        <p>Start with the issue most likely to affect users, safety, or reliability.</p>
      </article>
    </div>

    <article class="reviewer-priority-callout {primaryFinding ? primaryFinding.severity : result.risk_level}">
      <div class="reviewer-priority-top">
        <div>
          <div class="reviewer-kicker">Best Next Move</div>
          <h3>{primaryFinding ? primaryFinding.title : "Use the review plan below"}</h3>
        </div>
        <span class="chip chip-neutral">
          {primaryFinding ? severityLabel(primaryFinding.severity) : severityLabel(result.risk_level)}
        </span>
      </div>

      <p>{priorityAction}</p>

      {#if primaryFinding?.why_it_matters}
        <small>{primaryFinding.why_it_matters}</small>
      {/if}
    </article>
  </section>
{/if}
